import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;


/**
 * Exercise 6: Providing a GUI for BankAccount
 *
 * @author Dominik Harmim harmim6@gmail.com
 */
public class BankAccountViewer
{
	private JPanel mainPanel;
	private JButton withdrawButton;
	private JButton depositButton;
	private JTextField withdrawField;
	private JTextField depositField;
	private JButton showBalanceButton;
	private JLabel balanceLabel;

	private BankAccount account;


	public static void main(String[] args)
	{
		JFrame frame = new JFrame("BankAccountViewer");
		frame.setContentPane(new BankAccountViewer().mainPanel);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}


	private BankAccountViewer()
	{
		account = new BankAccount();
		showBalance();

		withdrawButton.addActionListener(e -> withdrawAction());
		depositButton.addActionListener(e -> depositAction());
		showBalanceButton.addActionListener(e -> showBalance());
	}


	private void withdrawAction()
	{
		if (!withdrawField.getText().equals("")) {
			try {
				account.withdraw(Double.parseDouble(withdrawField.getText()));
			} catch (NumberFormatException ignored) {
			}
		}
	}


	private void depositAction()
	{
		if (!depositField.getText().equals("")) {
			try {
				account.deposit(Double.parseDouble(depositField.getText()));
			} catch (NumberFormatException ignored) {
			}
		}
	}


	private void showBalance()
	{
		balanceLabel.setText(Double.toString(account.getBalance()));
	}


	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.setOpaque(true);
		mainPanel.setPreferredSize(new Dimension(400, 150));
		withdrawButton = new JButton();
		withdrawButton.setText("withdraw");
		mainPanel.add(withdrawButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		depositButton = new JButton();
		depositButton.setText("deposit");
		mainPanel.add(depositButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		withdrawField = new JTextField();
		mainPanel.add(withdrawField, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		depositField = new JTextField();
		mainPanel.add(depositField, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setEnabled(true);
		Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 20, label1.getFont());
		if (label1Font != null) label1.setFont(label1Font);
		label1.setText("Bank of Utopia");
		mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		showBalanceButton = new JButton();
		showBalanceButton.setText("show balance");
		mainPanel.add(showBalanceButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("your balance is:");
		mainPanel.add(label2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		balanceLabel = new JLabel();
		balanceLabel.setText("");
		mainPanel.add(balanceLabel, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}


	/**
	 * @noinspection ALL
	 */
	private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont)
	{
		if (currentFont == null) return null;
		String resultName;
		if (fontName == null) {
			resultName = currentFont.getName();
		} else {
			Font testFont = new Font(fontName, Font.PLAIN, 10);
			if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
				resultName = fontName;
			} else {
				resultName = currentFont.getName();
			}
		}
		return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
	}


	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return mainPanel;
	}
}
